version: 1.2
workflows:
- name: Subsample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Subsample.wdl
  testParameterFiles:
- name: FilterDipcall
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/FilterDipcall.wdl
  testParameterFiles:
- name: MapCCS
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/MapCCS.wdl
- name: Sniffles
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Sniffles.wdl  
- name: Pbsv
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Pbsv.wdl
- name: SVision
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SVision.wdl 
- name: Sawfish
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Sawfish.wdl  
- name: Cutesv
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Cutesv.wdl  
- name: Nanovar
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Nanovar.wdl  
- name: Svim
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Svim.wdl   
- name: Debreak
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Debreak.wdl    
- name: BcftoolsMergeNoDuplicates
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMergeNoDuplicates.wdl
- name: BcftoolsMergeDipcall
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMergeDipcall.wdl  
- name: VcfdistEvaluation
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/VcfdistEvaluation.wdl
  testParameterFiles:
- name: subset_n_samples_from_vcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/subset_n_samples_from_vcf.wdl
- name: subset_csv_samples_using_vcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/subset_csv_samples_using_vcf.wdl
- name: clean_vcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/clean_vcf.wdl
  testParameterFiles:
- name: fill_vcf_ref_alleles_from_fasta.wdl
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/fill_vcf_ref_alleles_from_fasta.wdl
  testParameterFiles:
