version: 1.2
workflows:
- name: Subsample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Subsample.wdl
  testParameterFiles:
- name: FilterDipcall
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/FilterDipcall.wdl
  testParameterFiles:
- name: MapCCS
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/MapCCS.wdl
- name: Sniffles
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Sniffles.wdl  
- name: Pbsv
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Pbsv.wdl
- name: SVision
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SVision.wdl 
- name: Sawfish
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Sawfish.wdl  
- name: Cutesv
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Cutesv.wdl  
- name: Nanovar
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Nanovar.wdl  
- name: Svim
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Svim.wdl   
- name: Debreak
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Debreak.wdl    
- name: BcftoolsMergeNoDuplicates
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMergeNoDuplicates.wdl
- name: BcftoolsMergeDipcall
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMergeDipcall.wdl  
- name: VcfdistEvaluation
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/VcfdistEvaluation.wdl
  testParameterFiles:
- name: subset_n_samples_from_vcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/subset_n_samples_from_vcf.wdl
- name: subset_csv_samples_using_vcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/subset_csv_samples_using_vcf.wdl
- name: clean_vcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/clean_vcf.wdl
  testParameterFiles:
- name: fill_vcf_ref_alleles_from_fasta
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/fill_vcf_ref_alleles_from_fasta.wdl
  testParameterFiles:
- name: Resolve
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Resolve.wdl  
- name: BcftoolsMergeIntrasample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMergeIntrasample.wdl
- name: BcftoolsMergeIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMergeIntersample.wdl
- name: SnifflesIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SnifflesIntersample.wdl
- name: PbsvIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PbsvIntersample.wdl
- name: Truvari
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Truvari.wdl
- name: Jasmine
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Jasmine.wdl
- name: JasminePrime
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/JasminePrime.wdl
- name: JasmineIntersample1
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/JasmineIntersample1.wdl
- name: Panpop
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Panpop.wdl
- name: Trgt
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Trgt.wdl
- name: BcftoolsMergeSvSnp
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMergeSvSnp.wdl
- name: Hifiasm
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Hifiasm.wdl
- name: TrgtMerge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TrgtMerge.wdl
- name: pav
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/pav.wdl
- name: BcftoolsMergeSvTrgt
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMergeSvTrgt.wdl  
- name: ResolvePav
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/ResolvePav.wdl  
- name: FilterSvim
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/FilterSvim.wdl
- name: KanpigGenotypeAndFilter
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/KanpigGenotypeAndFilter.wdl
